version: '3.7'

services:
  cdb:
    container_name: cdb
    image: cockroachdb/cockroach:v19.2.2
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - cdb-data:/cockroach/cockroach-data

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5-arm64
      container_name: es
      environment:
        - xpack.security.enabled=false
        - discovery.type=single-node
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
      cap_add:
        - IPC_LOCK
      volumes:
        - es-data:/usr/share/elasticsearch/data
      ports:
        - 9200:9200
        - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

volumes:
  es-data:
    driver: local
  cdb-data:
    driver: local

