// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Ahmed-Sermani/go-crawler/api/graph/proto (interfaces: GraphClient,Graph_LinksClient,Graph_EdgesClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	proto "github.com/Ahmed-Sermani/go-crawler/api/graph/proto"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
	metadata "google.golang.org/grpc/metadata"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockGraphClient is a mock of GraphClient interface.
type MockGraphClient struct {
	ctrl     *gomock.Controller
	recorder *MockGraphClientMockRecorder
}

// MockGraphClientMockRecorder is the mock recorder for MockGraphClient.
type MockGraphClientMockRecorder struct {
	mock *MockGraphClient
}

// NewMockGraphClient creates a new mock instance.
func NewMockGraphClient(ctrl *gomock.Controller) *MockGraphClient {
	mock := &MockGraphClient{ctrl: ctrl}
	mock.recorder = &MockGraphClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraphClient) EXPECT() *MockGraphClientMockRecorder {
	return m.recorder
}

// Edges mocks base method.
func (m *MockGraphClient) Edges(arg0 context.Context, arg1 *proto.Range, arg2 ...grpc.CallOption) (proto.Graph_EdgesClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Edges", varargs...)
	ret0, _ := ret[0].(proto.Graph_EdgesClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Edges indicates an expected call of Edges.
func (mr *MockGraphClientMockRecorder) Edges(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Edges", reflect.TypeOf((*MockGraphClient)(nil).Edges), varargs...)
}

// Links mocks base method.
func (m *MockGraphClient) Links(arg0 context.Context, arg1 *proto.Range, arg2 ...grpc.CallOption) (proto.Graph_LinksClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Links", varargs...)
	ret0, _ := ret[0].(proto.Graph_LinksClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Links indicates an expected call of Links.
func (mr *MockGraphClientMockRecorder) Links(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Links", reflect.TypeOf((*MockGraphClient)(nil).Links), varargs...)
}

// RemoveStaleEdges mocks base method.
func (m *MockGraphClient) RemoveStaleEdges(arg0 context.Context, arg1 *proto.RemoveStaleEdgesQuery, arg2 ...grpc.CallOption) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemoveStaleEdges", varargs...)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveStaleEdges indicates an expected call of RemoveStaleEdges.
func (mr *MockGraphClientMockRecorder) RemoveStaleEdges(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveStaleEdges", reflect.TypeOf((*MockGraphClient)(nil).RemoveStaleEdges), varargs...)
}

// UpsertEdge mocks base method.
func (m *MockGraphClient) UpsertEdge(arg0 context.Context, arg1 *proto.Edge, arg2 ...grpc.CallOption) (*proto.Edge, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpsertEdge", varargs...)
	ret0, _ := ret[0].(*proto.Edge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertEdge indicates an expected call of UpsertEdge.
func (mr *MockGraphClientMockRecorder) UpsertEdge(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertEdge", reflect.TypeOf((*MockGraphClient)(nil).UpsertEdge), varargs...)
}

// UpsertLink mocks base method.
func (m *MockGraphClient) UpsertLink(arg0 context.Context, arg1 *proto.Link, arg2 ...grpc.CallOption) (*proto.Link, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpsertLink", varargs...)
	ret0, _ := ret[0].(*proto.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertLink indicates an expected call of UpsertLink.
func (mr *MockGraphClientMockRecorder) UpsertLink(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertLink", reflect.TypeOf((*MockGraphClient)(nil).UpsertLink), varargs...)
}

// MockGraph_LinksClient is a mock of Graph_LinksClient interface.
type MockGraph_LinksClient struct {
	ctrl     *gomock.Controller
	recorder *MockGraph_LinksClientMockRecorder
}

// MockGraph_LinksClientMockRecorder is the mock recorder for MockGraph_LinksClient.
type MockGraph_LinksClientMockRecorder struct {
	mock *MockGraph_LinksClient
}

// NewMockGraph_LinksClient creates a new mock instance.
func NewMockGraph_LinksClient(ctrl *gomock.Controller) *MockGraph_LinksClient {
	mock := &MockGraph_LinksClient{ctrl: ctrl}
	mock.recorder = &MockGraph_LinksClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraph_LinksClient) EXPECT() *MockGraph_LinksClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockGraph_LinksClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockGraph_LinksClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockGraph_LinksClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockGraph_LinksClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockGraph_LinksClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockGraph_LinksClient)(nil).Context))
}

// Header mocks base method.
func (m *MockGraph_LinksClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockGraph_LinksClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockGraph_LinksClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockGraph_LinksClient) Recv() (*proto.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*proto.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockGraph_LinksClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockGraph_LinksClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockGraph_LinksClient) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockGraph_LinksClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockGraph_LinksClient)(nil).RecvMsg), arg0)
}

// SendMsg mocks base method.
func (m *MockGraph_LinksClient) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockGraph_LinksClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockGraph_LinksClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method.
func (m *MockGraph_LinksClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockGraph_LinksClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockGraph_LinksClient)(nil).Trailer))
}

// MockGraph_EdgesClient is a mock of Graph_EdgesClient interface.
type MockGraph_EdgesClient struct {
	ctrl     *gomock.Controller
	recorder *MockGraph_EdgesClientMockRecorder
}

// MockGraph_EdgesClientMockRecorder is the mock recorder for MockGraph_EdgesClient.
type MockGraph_EdgesClientMockRecorder struct {
	mock *MockGraph_EdgesClient
}

// NewMockGraph_EdgesClient creates a new mock instance.
func NewMockGraph_EdgesClient(ctrl *gomock.Controller) *MockGraph_EdgesClient {
	mock := &MockGraph_EdgesClient{ctrl: ctrl}
	mock.recorder = &MockGraph_EdgesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraph_EdgesClient) EXPECT() *MockGraph_EdgesClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockGraph_EdgesClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockGraph_EdgesClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockGraph_EdgesClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockGraph_EdgesClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockGraph_EdgesClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockGraph_EdgesClient)(nil).Context))
}

// Header mocks base method.
func (m *MockGraph_EdgesClient) Header() (metadata.MD, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Header")
	ret0, _ := ret[0].(metadata.MD)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Header indicates an expected call of Header.
func (mr *MockGraph_EdgesClientMockRecorder) Header() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Header", reflect.TypeOf((*MockGraph_EdgesClient)(nil).Header))
}

// Recv mocks base method.
func (m *MockGraph_EdgesClient) Recv() (*proto.Edge, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*proto.Edge)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockGraph_EdgesClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockGraph_EdgesClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m *MockGraph_EdgesClient) RecvMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecvMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockGraph_EdgesClientMockRecorder) RecvMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockGraph_EdgesClient)(nil).RecvMsg), arg0)
}

// SendMsg mocks base method.
func (m *MockGraph_EdgesClient) SendMsg(arg0 interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMsg", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockGraph_EdgesClientMockRecorder) SendMsg(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockGraph_EdgesClient)(nil).SendMsg), arg0)
}

// Trailer mocks base method.
func (m *MockGraph_EdgesClient) Trailer() metadata.MD {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trailer")
	ret0, _ := ret[0].(metadata.MD)
	return ret0
}

// Trailer indicates an expected call of Trailer.
func (mr *MockGraph_EdgesClientMockRecorder) Trailer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trailer", reflect.TypeOf((*MockGraph_EdgesClient)(nil).Trailer))
}
